# Generated by Django 5.0.2 on 2024-03-18 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
